spring.application.name=auditoria-bd

# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/auditoria_bd
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate - el esquema ya existe, Hibernate solo valida el mapeo
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

server.port=8080
