-- =============================================================================
-- Monitor de Salud de Oracle - tablas de historico
-- Ejecutar conectado como el usuario de aplicacion (auditoria) en XEPDB1.
--
-- Diseno reducido a dos tablas: las vistas dinamicas de Oracle (V$..., DBA_...)
-- ya son la fuente de verdad "en vivo" de procesos/memoria/archivos, asi que no
-- se duplican datos crudos en tablas propias. Lo unico que hace falta persistir
-- para cumplir el requisito de "guardar historial" es la serie de indices
-- calculados (IP/IM/IA/ISBD + estado) y el registro de alertas generadas.
-- Ver README.md para la justificacion completa de la metodologia.
-- =============================================================================

CREATE TABLE monitor_indice (
    id_monitor_indice   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora          TIMESTAMP NOT NULL,
    indicador_procesos  NUMBER(5,2) NOT NULL,
    indicador_memoria   NUMBER(5,2) NOT NULL,
    indicador_archivos  NUMBER(5,2) NOT NULL,
    indice_salud        NUMBER(5,2) NOT NULL,
    estado              VARCHAR2(20) NOT NULL
);

CREATE TABLE monitor_alerta (
    id_monitor_alerta   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora          TIMESTAMP NOT NULL,
    componente          VARCHAR2(20) NOT NULL,
    variable            VARCHAR2(60) NOT NULL,
    valor               VARCHAR2(60) NOT NULL,
    umbral              VARCHAR2(60),
    nivel               VARCHAR2(20) NOT NULL,
    descripcion         VARCHAR2(300) NOT NULL
);

CREATE INDEX idx_monitor_indice_fecha ON monitor_indice (fecha_hora);
CREATE INDEX idx_monitor_alerta_fecha ON monitor_alerta (fecha_hora);
