-- =============================================================================
-- Monitor de Salud de Oracle - tablas de historico
-- Ejecutar conectado como el usuario de aplicacion (auditoria) en XEPDB1.
--
-- Modelo de datos (sigue el esquema de 6 conceptos de la seccion 24 de la
-- guia, MONITOR_INSTANCIA excluido: en este proyecto solo se monitorea una
-- instancia, no aporta ninguna variable propia que no viva ya en las demas
-- tablas):
--   MONITOR_INDICE       -> historico del ISBD combinado + IP/IM/IA (resumen)
--   MONITOR_PROCESOS     -> historico de las variables CRUDAS de procesos
--   MONITOR_MEMORIA      -> historico de las variables CRUDAS de memoria
--   MONITOR_ARCHIVOS     -> historico de las variables CRUDAS de archivos (resumen)
--   MONITOR_TABLESPACE   -> historico del % de uso de CADA tablespace (N filas/ciclo)
--   MONITOR_ALERTA       -> alertas, con "relacion" simple: condiciones que
--                           persisten entre ciclos actualizan la misma fila
--                           (fecha_hora + ocurrencias) en vez de duplicarse.
--
-- Las vistas dinamicas de Oracle (V$..., DBA_...) siguen siendo la fuente de
-- verdad del estado ACTUAL; estas tablas existen solo para poder responder
-- preguntas de EVOLUCION en el tiempo (seccion 23 de la guia) que las vistas
-- V$ no pueden responder por si solas (son "instantaneas", no historico).
-- Ver README.md para la justificacion completa de la metodologia.
-- =============================================================================

CREATE TABLE monitor_indice (
    id_monitor_indice   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora          TIMESTAMP NOT NULL,
    indicador_procesos  NUMBER(5,2) NOT NULL,
    indicador_memoria   NUMBER(5,2) NOT NULL,
    indicador_archivos  NUMBER(5,2) NOT NULL,
    indice_salud        NUMBER(5,2) NOT NULL,
    estado              VARCHAR2(20) NOT NULL
);

CREATE TABLE monitor_procesos (
    id_monitor_procesos     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora              TIMESTAMP NOT NULL,
    indicador_procesos      NUMBER(5,2) NOT NULL,
    uso_procesos_pct        NUMBER(6,3) NOT NULL,
    uso_sesiones_pct        NUMBER(6,3) NOT NULL,
    sesiones_bloqueadas     NUMBER NOT NULL,
    operaciones_prolongadas NUMBER NOT NULL
);

CREATE TABLE monitor_memoria (
    id_monitor_memoria   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora           TIMESTAMP NOT NULL,
    indicador_memoria    NUMBER(5,2) NOT NULL,
    cache_hit_pga_pct    NUMBER(6,3) NOT NULL,
    over_allocation_pga  NUMBER NOT NULL,
    uso_sga_pct          NUMBER(6,3) NOT NULL
);

CREATE TABLE monitor_archivos (
    id_monitor_archivos  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora           TIMESTAMP NOT NULL,
    indicador_archivos   NUMBER(5,2) NOT NULL,
    datafiles_online     NUMBER NOT NULL,
    datafiles_total      NUMBER NOT NULL,
    tempfiles_online     NUMBER NOT NULL,
    tempfiles_total      NUMBER NOT NULL,
    redologs_invalidos   NUMBER NOT NULL
);

CREATE TABLE monitor_tablespace (
    id_monitor_tablespace  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora             TIMESTAMP NOT NULL,
    tablespace_name        VARCHAR2(30) NOT NULL,
    porcentaje_usado       NUMBER(6,3) NOT NULL
);

CREATE TABLE monitor_alerta (
    id_monitor_alerta   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_primera       TIMESTAMP NOT NULL,
    fecha_hora          TIMESTAMP NOT NULL,
    componente          VARCHAR2(20) NOT NULL,
    variable            VARCHAR2(60) NOT NULL,
    valor               VARCHAR2(60) NOT NULL,
    umbral              VARCHAR2(60),
    nivel               VARCHAR2(20) NOT NULL,
    descripcion         VARCHAR2(300) NOT NULL,
    ocurrencias         NUMBER DEFAULT 1 NOT NULL
);

CREATE INDEX idx_monitor_indice_fecha ON monitor_indice (fecha_hora);
CREATE INDEX idx_monitor_procesos_fecha ON monitor_procesos (fecha_hora);
CREATE INDEX idx_monitor_memoria_fecha ON monitor_memoria (fecha_hora);
CREATE INDEX idx_monitor_archivos_fecha ON monitor_archivos (fecha_hora);
CREATE INDEX idx_monitor_tbs_fecha ON monitor_tablespace (fecha_hora);
CREATE INDEX idx_monitor_tbs_nombre ON monitor_tablespace (tablespace_name, fecha_hora);
CREATE INDEX idx_monitor_alerta_fecha ON monitor_alerta (fecha_hora);
CREATE INDEX idx_monitor_alerta_cond ON monitor_alerta (componente, variable, fecha_hora);
