-- =============================================================================
-- Esquema principal de la aplicacion auditoria-bd (8 tablas de negocio)
-- Ejecutar conectado como el usuario de aplicacion (auditoria) en XEPDB1,
-- ANTES de sql/monitor_oracle.sql y ANTES de arrancar la aplicacion (Hibernate
-- esta en modo "validate": necesita que el esquema ya exista).
--
-- Generado a partir de los mapeos @Entity en src/main/java/.../entity/
-- (identidad NUMBER GENERATED BY DEFAULT AS IDENTITY, VARCHAR2, CLOB para los
-- campos @Lob, NUMBER(1) para los boolean, tal como indica el README).
-- =============================================================================

CREATE TABLE usuario (
    id_usuario       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR2(100) NOT NULL,
    correo           VARCHAR2(150) NOT NULL UNIQUE,
    contrasena_hash  VARCHAR2(255) NOT NULL,
    rol              VARCHAR2(20) NOT NULL,
    activo           NUMBER(1) DEFAULT 1 NOT NULL,
    fecha_creacion   TIMESTAMP NOT NULL
);

CREATE TABLE organizacion (
    id_organizacion   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR2(150) NOT NULL,
    area_evaluada     VARCHAR2(150) NOT NULL,
    administrador_bd  VARCHAR2(150),
    fecha_registro    TIMESTAMP NOT NULL
);

CREATE TABLE control (
    id_control  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR2(20) NOT NULL UNIQUE,
    nombre      VARCHAR2(150) NOT NULL,
    dominio     VARCHAR2(50) NOT NULL,
    objetivo    VARCHAR2(300),
    descripcion CLOB,
    peso        VARCHAR2(10) NOT NULL,
    afecta_c    NUMBER(1) NOT NULL,
    afecta_i    NUMBER(1) NOT NULL,
    afecta_d    NUMBER(1) NOT NULL
);

CREATE TABLE pregunta (
    id_pregunta  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_control   NUMBER NOT NULL,
    texto        VARCHAR2(300) NOT NULL,
    orden        NUMBER NOT NULL,
    CONSTRAINT fk_pregunta_control FOREIGN KEY (id_control) REFERENCES control (id_control)
);

CREATE TABLE auditoria (
    id_auditoria     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_organizacion  NUMBER NOT NULL,
    id_auditor       NUMBER NOT NULL,
    fecha_auditoria  DATE NOT NULL,
    estado           VARCHAR2(20) NOT NULL,
    fecha_creacion   TIMESTAMP NOT NULL,
    CONSTRAINT fk_auditoria_organizacion FOREIGN KEY (id_organizacion) REFERENCES organizacion (id_organizacion),
    CONSTRAINT fk_auditoria_usuario FOREIGN KEY (id_auditor) REFERENCES usuario (id_usuario)
);

CREATE TABLE respuesta (
    id_respuesta  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_auditoria  NUMBER NOT NULL,
    id_pregunta   NUMBER NOT NULL,
    valor         VARCHAR2(10) NOT NULL,
    observacion   CLOB,
    evidencia     VARCHAR2(300),
    CONSTRAINT fk_respuesta_auditoria FOREIGN KEY (id_auditoria) REFERENCES auditoria (id_auditoria),
    CONSTRAINT fk_respuesta_pregunta FOREIGN KEY (id_pregunta) REFERENCES pregunta (id_pregunta),
    CONSTRAINT uk_respuesta_auditoria_pregunta UNIQUE (id_auditoria, id_pregunta)
);

CREATE TABLE resultado_control (
    id_resultado_control     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_auditoria             NUMBER NOT NULL,
    id_control               NUMBER NOT NULL,
    porcentaje_cumplimiento  NUMBER(5,2),
    nivel_madurez            NUMBER(2),
    riesgo_control           NUMBER(5,2),
    CONSTRAINT fk_resctrl_auditoria FOREIGN KEY (id_auditoria) REFERENCES auditoria (id_auditoria),
    CONSTRAINT fk_resctrl_control FOREIGN KEY (id_control) REFERENCES control (id_control),
    CONSTRAINT uk_resctrl_auditoria_control UNIQUE (id_auditoria, id_control)
);

CREATE TABLE resultado_auditoria (
    id_resultado_auditoria   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_auditoria             NUMBER NOT NULL UNIQUE,
    madurez_general          NUMBER(4,2),
    riesgo_confidencialidad  NUMBER(5,2),
    riesgo_integridad        NUMBER(5,2),
    riesgo_disponibilidad    NUMBER(5,2),
    indice_riesgo_general    NUMBER(5,2),
    fecha_calculo            TIMESTAMP NOT NULL,
    CONSTRAINT fk_resaud_auditoria FOREIGN KEY (id_auditoria) REFERENCES auditoria (id_auditoria)
);

CREATE INDEX idx_pregunta_control ON pregunta (id_control);
CREATE INDEX idx_auditoria_organizacion ON auditoria (id_organizacion);
CREATE INDEX idx_auditoria_auditor ON auditoria (id_auditor);
CREATE INDEX idx_respuesta_auditoria ON respuesta (id_auditoria);
CREATE INDEX idx_respuesta_pregunta ON respuesta (id_pregunta);
CREATE INDEX idx_resctrl_auditoria ON resultado_control (id_auditoria);
CREATE INDEX idx_resctrl_control ON resultado_control (id_control);
